---
- name: Install Packages For Adding OpenJDK Repository.
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'wget', 'dirmngr', 'gnupg', 'software-properties-common']
    state: present
    update_cache: yes
  no_log: no
  become: true

- name: Import Adoptopenjdk GPG Key.
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
  become: true

- name: Add Adoptopenjdk Repository.
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb {{ ansible_distribution_release }} main
    state: present
    update_cache: no
  become: true

- name: Install openjdk-11-jre-headless.
  apt:
    name: 'openjdk-11-jre-headless'
    state: present
  become: true

- name: Remove Old Versions of Java.
  apt:
    name: 'default-jdk'
    state: absent
  become: true